clone:
  git:
    image: plugins/git:next

pipeline:
  lint:
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    image: golang:1.16
    commands:
      - make test

  build:
    image: golang:1.16
    commands:
      - make build
