variables:
  - &golang 'golang:1.20'

steps:
  lint:
    group: test
    image: *golang
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: *golang
    commands:
      - make test

  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      dry_run: true
      repo: woodpeckerci/plugin-s3
      tags: latest
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,windows/amd64,darwin/amd64,darwin/arm64,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: pull_request

  publish-next:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      repo: woodpeckerci/plugin-s3
      tags: next
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,windows/amd64,darwin/amd64,darwin/arm64,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      repo: woodpeckerci/plugin-s3
      tag: [latest, "${CI_COMMIT_TAG}"]
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,windows/amd64,darwin/amd64,darwin/arm64,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64
    secrets: [docker_username, docker_password]
    when:
      event: tag
