clone:
  git:
    image: plugins/git:next

pipeline:
  lint:
    image: golang:1.16
    commands:
      - make vet
      - make formatcheck

  test:
    image: golang:1.16
    commands:
      - make test

  build:
    image: golang:1.16
    commands:
      - make build

  dryrun:
    image: plugins/docker:linux-amd64
    settings:
      dockerfile: docker/Dockerfile.linux.amd64
      dry_run: true
      repo: woodpeckerci/plugin-s3
      tags: linux-amd64
    when:
      event: pull_request

  publish:
    image: plugins/docker:linux-amd64
    settings:
      dockerfile: docker/Dockerfile.linux.amd64
      repo: woodpeckerci/plugin-s3
      tags: linux-amd64
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      branch: master
      event: push
