variables:
  - &golang 'golang:1.22'
  - &build_plugin 'woodpeckerci/plugin-docker-buildx:4.0.0'
  - base_settings: &base_buildx_settings
      platforms: 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,windows/amd64,darwin/amd64,darwin/arm64,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64'
      dockerfile: Dockerfile.multiarch
      auto_tag: true
      repo: woodpeckerci/plugin-s3
  - &login_setting # Default DockerHub login
    - registry: https://index.docker.io/v1/
      username: woodpeckerbot
      password:
        from_secret: docker_password

when:
  - event: tag
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  vendor:
    image: *golang
    commands:
      - go mod vendor

  publish:
    image: *build_plugin
    depends_on: [ vendor ]
    settings:
      <<: *base_buildx_settings
      logins: *login_setting
    when:
      event: [push, tag]
      branch: ${CI_REPO_DEFAULT_BRANCH}
