variables:
  - &golang 'golang:1.21'

when:
  - event: pull_request
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  lint:
    group: test
    image: *golang
    commands:
      - make vet
      - make formatcheck

  test:
    group: test
    image: *golang
    commands:
      - make test

  build:
    image: woodpeckerci/plugin-docker-buildx:2.2.0
    settings:
      dockerfile: Dockerfile.multiarch
      dry_run: true
      repo: woodpeckerci/plugin-s3
      tags: latest
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,windows/amd64,darwin/amd64,darwin/arm64,freebsd/arm64,freebsd/amd64,openbsd/arm64,openbsd/amd64
